### ISSUE TITLE
Review Kp 6 Selbstführung

### ISSUE THREAD

**Issue by fabwu** [wuethrich44/zusammenfassung-itpmf#24]

**Comment by alexsuter** [comment]
Gemäss Stoffabgrenzung sind nur die ersten Kapitel relevant. Darum habe die irrelevanten Kapitel nicht dokumentiert. Die Lernziele sind abgedeckt und auch die möglichen MEP Fragen können mit dem Dokumentiertem beantworten werden.
Ich bin mir nicht ganz sicher ob wir vllt. noch etwas präziser auf die somatischer Marker eingehen sollten. Die Skala habe ich nicht ganz verstanden?!

**Comment by fabwu** [comment]
Ich denke die letschte folie sind würklich für nüt. Ich ha no somatische marker und zielsetzig verbesseret.
