### ISSUE TITLE
Wieviel Tage sind PersonenMonate und PersonenJahre?

### ISSUE THREAD

**Issue by alexsuter** [wuethrich44/zusammenfassung-itpmf#36]
Man rechnet in PT - Personen Tage.

Ist ein Personen Monat = 20 x 1PT = 20PT
Und ein Personen Jahr = 20 x 1PT \* 12 = 240PT

Stimmt das?

**Comment by fabwu** [comment]
![image](https://cloud.githubusercontent.com/assets/6050639/8155198/21f44810-1342-11e5-8454-fed84f4f1277.png)
