### ISSUE TITLE
Somatische Marker - Wertungssystem?

### ISSUE THREAD

**Issue by alexsuter** [wuethrich44/zusammenfassung-itpmf#37]
Ein somatischer Marker ist jeder körperliche Reaktion, jedes mentale Bild, Szene, Erinnerung die unmittelbar auf die Frage/Begriff wahrnehmbar wird.

Bsp: Kribbeln im Bauch, Erregung, Kneifen

Dieses Gefühl kann positiv oder negativ sein. Darum gibt es zwei Skalen. Eine für das positive Gefühl (Lust) und eine für das negative Gefühl (Abscheu).

Ich verstehe nun nicht was folgendes heisst -0/+70 .   -0 Lust und +70 Abscheu? Hää? Was bedeutet das, und wie muss ich vorgehen, wenn ich einen Zielsatz bewerten will?

**Comment by fabwu** [comment]
Du muesches gsprüüre... ;)

**Comment by alexsuter** [comment]
Das Minus steht immer für die Abscheu, das Plus steht immer für die Lust. Somit ist die Reihenfolge egal.

Wenn steht, dass man mind. einen Energiepegel von -0/+70 haben sollte, bedeutet das, dass man wirklich 0 Abscheu haben sollte. Und mind. 70 Lust. 
Also nicht einfach zusammenrechnen: -20/+90 zu +70 rechnen. Da habe ich -20 Abscheu,  und so wird es schwierig mein Ziel zu erreichen.
