### ISSUE TITLE
Advisory Board

### ISSUE THREAD

**Issue by alexsuter** [wuethrich44/zusammenfassung-itpmf#39]
Ich habe mir folgende Notiz gemacht: Advisory Board = Kunden-Board, Zentrale Stelle für Kunden. Aufzeigen was man im Projekt macht,

In den Folien steht: Board besteht aus Experten, Schlüsselpersonen und Kunden des Projekts. Es 'berät' das Projekt, gibt Feedbacks zu Lösungen und ist ein wichtiges Bindeglied zu den Benutzern. Es hat jedoch keine Entscheidungskompetenzen.

Ich bin der Meinung, dass meine Notizen falsch sind und das in den Folien korrekt ist. Oder? Siehe auch https://en.wikipedia.org/wiki/Advisory_board

Meine Frage: Gibt es ein Kunden-Board? Speziell für Kunden? Wie nennt sich das, ich nehme an ich habe mir diesen Begriff nicht aufgeschrieben.

**Comment by fabwu** [comment]
Das mit dem Advisory Board und den Experten ist richtig so. Ich denke das was am ehsten an ein Kunden-Board herankommt ist der Steuerungsausschuss (Unterstützt Auftraggeber). 

![image](https://cloud.githubusercontent.com/assets/6050639/8155171/c687c844-1341-11e5-8d86-a3f01b22453b.png)
