### ISSUE TITLE
Review Kp 02 Wahrnehmung & Kommunikation

### ISSUE THREAD

**Issue by alexsuter** [wuethrich44/zusammenfassung-itpmf#6]

**Comment by alexsuter** [comment]
i'm afraid. 

chöntsch bitte noch churz luege, öbs das bezüglich integro langet. er het schono es paar folie dine, aber ich glaube es langed wemmers konzept verstaht?!

**Comment by fabwu** [comment]
Ich denke das längt eso für details chame immer no ind folie go luege
