### ISSUE TITLE
Review Kp 04 Moderation & Informelle Führung

### ISSUE THREAD

**Issue by alexsuter** [wuethrich44/zusammenfassung-itpmf#8]

**Comment by fabwu** [comment]
@alexander-suter Kannst du mal darüber schauen. Ich würde es noch etwas kürzen ich war nicht dabei darum weiss ich nicht was wichtig ist...

**Comment by alexsuter** [comment]
@wuethrich44 Ich ha no Sache ergänzt - vo de MEP Folie. Süsch ok. Es gid zu dem Thema kei Folie? Ich bin ebe au nid gsi. Ich würs zum Abschluss glich no churz am Simon gä, er isch ja a dere epische Moderation dete gsi :+1:
